### ISSUE TITLE
install kms error

### ISSUE THREAD

**Issue by suoc** [pkgs-cloud/kurento#1]
---> Package libXau-devel.x86_64 0:1.0.8-2.1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: dyninst-8.2.0-2.el7.x86_64 (@anaconda)
           Requires: libboost_system-mt.so.1.53.0()(64bit)
           Removing: boost-system-1.53.0-25.el7.x86_64 (@anaconda)
               libboost_system-mt.so.1.53.0()(64bit)
           Updated By: boost-system-1.55.0-8.el7.x86_64 (pkgs.cloud-kurento)
               Not found
           Available: boost-system-1.53.0-26.el7.x86_64 (base)
               libboost_system-mt.so.1.53.0()(64bit)
Error: Package: dyninst-8.2.0-2.el7.x86_64 (@anaconda)
           Requires: libboost_thread-mt.so.1.53.0()(64bit)
           Removing: boost-thread-1.53.0-25.el7.x86_64 (@anaconda)
               libboost_thread-mt.so.1.53.0()(64bit)
           Updated By: boost-thread-1.55.0-8.el7.x86_64 (pkgs.cloud-kurento)
               Not found
           Available: boost-thread-1.53.0-26.el7.x86_64 (base)
               libboost_thread-mt.so.1.53.0()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by arthurpro** [comment]
From your error I can say that you have a package `libXau-devel` which depends on Boost v1.53
Kurento needs Boost v1.55
If you uninstall `libXau-devel` you should be able to install Kurento.
Try the following

```
yum erase libXau-devel
yum install kms
```

If you run into more errors, that means you have other conflicting packages.

It is recommended that you install Kurento on a clean minimal OS installation.

**Comment by trung1008** [comment]
I still have same issuse. Please help me :( 
 
Package libXau-devel.x86_64 0:1.0.8-2.1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 1:librados2-0.94.5-2.el7.x86_64 (@base)
           Requires: libboost_thread-mt.so.1.53.0()(64bit)
           Removing: boost-thread-1.53.0-27.el7.x86_64 (@base)
               libboost_thread-mt.so.1.53.0()(64bit)
           Updated By: boost-thread-1.55.0-8.el7.x86_64 (pkgs.cloud-kurento)
               Not found

**Comment by arthurpro** [comment]
@trung1008 from what I can see you have a conflicting package librados2. and you have to remove it first.
`yum erase librados2`
then retry. if you see more conflicts, just remove those packages one by one.

for best results Kurento has to be installed on a fresh minimal install OS

**Comment by trung1008** [comment]
oh nice, Thanks @arthurpro 👍
