### ISSUE TITLE
Getting RPM Specs to build my own RPM package

### ISSUE THREAD

**Issue by thunder-spb** [pkgs-cloud/kurento#2]
Hi guys,

Could you share RPM spec files. I want to build my own custom RPM file.

Thanks in advance!

**Comment by arthurpro** [comment]
Hello,

Sorry for the late response. Do you still need them?

**Comment by thunder-spb** [comment]
Yes! It will be awesome, @arthurpro !

**Comment by thunder-spb** [comment]
@arthurpro just a kindly reminder :)

**Comment by arthurpro** [comment]
@thunder-spb rpm specs are here https://github.com/pkgs-cloud/kurento/tree/master/SPECS

**Comment by thunder-spb** [comment]
Great! Thanks @arthurpro !
